connectercise/urls.py
from django.urls import path
from connectercise import views

app_name = 'connectercise'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('explore/', views.explore, name='explore'),
    path('sports/', views.sports, name='sports'),
    path('sport/<slug:sport_name_slug>/', views.show_sport, name='show_sport'),
    path('sport/<slug:sport_name_slug>/<slug:request_name_slug>', views.show_request, name='show_request'),
    path('sport/<slug:sport_name_slug>/<slug:request_name_slug>/accept', views.accept_request, name='accept_request'),
    path('sport/<slug:sport_name_slug>/<slug:request_name_slug>/delete', views.delete_request, name='delete_request'),
    path('add_sport/', views.add_sport, name='add_sport'),
    path('sport/<slug:sport_name_slug>/add_request/', views.add_sport_request, name='add_sport_request'),
    path('user/<slug:user_profile_slug>/', views.show_user, name='show_user'),
    path('user/<slug:user_profile_slug>/settings/', views.user_settings, name='user_settings'),
    path('user/<slug:user_profile_slug>/delete/', views.user_delete, name='user_delete'),
    path('add_request/', views.add_request, name='add_request'),
    path('search/', views.search, name='search'),
    path('sport/<slug:sport_name_slug>/<slug:request_name_slug>/accept_request', views.accept_request, name='accept_request'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service'),
]

connectercise_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('connectercise.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

connectercise/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from registration.signals import user_registered
import uuid

# Sport Model that contains Requests; the names are supposed to be unique
class Sport(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True)
    picture = models.ImageField(upload_to='sports', default='sports/default.jpg')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Sport, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

# Requests that belong to Sports; they have a unique ID generated through 'uuid' that are also used as slugs
class SportRequest(models.Model):
    sport = models.ForeignKey(Sport, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    request_id = models.CharField(max_length=128,primary_key=True)
    suggested_date = models.DateField(null=True, blank=True, help_text='MM/DD/YY (optional HH:MM)')
    location = models.CharField(max_length=512)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    desc = models.CharField(max_length=1024)
    completed = models.BooleanField(default=False)
    picture = models.ImageField(upload_to='requests', blank=True)

    def save(self, *args, **kwargs):
        self.request_id = str(uuid.uuid4().int)
        self.slug = slugify(self.request_id)
        super(SportRequest, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

# UserProfile Model that contains 'auth_user', a picture and slug for their URL
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', default='profile_images/default.jpg')
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username

# Comment Model
class Comment(models.Model):
    request = models.ForeignKey(SportRequest,on_delete=models.CASCADE,related_name='comments')
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

# Used to create a UserProfile after creating 'auth_user'
def createUserProfile(sender, user, request, **kwargs):
    UserProfile.objects.get_or_create(user=user)

user_registered.connect(createUserProfile)

connectercise/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from connectercise.models import SportRequest, Sport, UserProfile, Comment
from location_field.forms.plain import PlainLocationField

# Adding a Sport (Only for Superusers)
class SportForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the sport name.")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Sport
        fields = ('name',)

# Adding a Request specifying a sport
class RequestForm(forms.ModelForm):
    title = forms.CharField(max_length=128)
    desc = forms.CharField(widget=forms.Textarea)
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    suggested_date = forms.DateTimeField(widget=forms.SelectDateWidget(), required=False)
    city = forms.CharField(max_length=255, help_text="Search Map", initial="Glasgow")
    location = PlainLocationField(based_fields=['city'], zoom=7, initial='55.87155490317328,-4.288530349731445', help_text="Move the pin around.")

    class Meta:
        model = SportRequest
        exclude = ('creator','slug','request_id','completed')
    
    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data

    field_order = ['sport','title', 'desc', 'views','suggested_date','city','location','picture']

# Adding a Request corresponding to a Sport (i.e. sport is pre-filled because of URL)
class SportRequestForm(forms.ModelForm):
    title = forms.CharField(max_length=128)
    desc = forms.CharField(widget=forms.Textarea)
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    suggested_date = forms.DateTimeField(widget=forms.SelectDateWidget(), required=False)
    city = forms.CharField(max_length=255, help_text="Search Map", initial="Glasgow")
    location = PlainLocationField(based_fields=['city'], zoom=7, initial='55.87155490317328,-4.288530349731445', help_text="Move the pin around.")

    class Meta:
        model = SportRequest
        exclude = ('creator','slug','sport','request_id','completed')
    
    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data

    field_order = ['title', 'desc', 'views','suggested_date','city','location','picture']

# User Registration Form
class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')

# User Settings Form
class UserForm2(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email','first_name','last_name')

# UserProfile Settings Form
class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('picture',)

# Comment Form
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

connectercise/views.py
from datetime import datetime, timedelta
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
from django.urls import reverse
from connectercise.models import Sport, SportRequest, UserProfile
from django.db.models import F
from django.contrib.auth.models import User
from connectercise.forms import SportForm, RequestForm, UserForm, UserProfileForm, CommentForm, SportRequestForm, UserForm2
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def index(request):
    
    # If user recently registered, redirect them to User Settings to fill in their full name and picture
    if request.user.is_authenticated:
        if timezone.now() - request.user.date_joined < timedelta(seconds=5):
            return redirect(reverse('connectercise:user_settings', kwargs={'user_profile_slug': request.user}))

    sport_list = Sport.objects.all()[:5]
    request_list = SportRequest.objects.order_by('-views')[:5]
    context_dict = {}
    context_dict['sports'] = sport_list
    context_dict['requests'] = request_list
    return render(request, 'connectercise/index.html', context=context_dict)



# Render About Page
def about(request):
    context_dict = {}
    return render(request, 'connectercise/about.html', context=context_dict)



# Render Explore Page
def explore(request):
    sport_list = Sport.objects.all()[:5]
    request_list = SportRequest.objects.order_by('-views')[:5]
    context_dict = {}
    context_dict['sports'] = sport_list
    context_dict['requests'] = request_list
    return render(request, 'connectercise/explore.html', context=context_dict)



# Render Sports Page
def sports(request):
    sport_list = Sport.objects.all()[:5]
    context_dict = {}
    context_dict['sports'] = sport_list
    return render(request, 'connectercise/sports.html', context=context_dict)



# Show Requests of a Specified Sport
def show_sport(request, sport_name_slug):
    context_dict = {}
    try:
        sport = Sport.objects.get(slug=sport_name_slug)
        requests = SportRequest.objects.filter(sport=sport)
        context_dict['requests'] = requests
        context_dict['sport'] = sport
    except Sport.DoesNotExist:
        context_dict['sport'] = None
        context_dict['requests'] = None
    return render(request, 'connectercise/sport.html', context=context_dict)



# Show details of a SportRequest
def show_request(request, sport_name_slug, request_name_slug):
    context_dict = {}
    
    try:
        s_request = SportRequest.objects.get(slug=request_name_slug)
        SportRequest.objects.filter(slug=request_name_slug).update(views=s_request.views+1)
        context_dict['request'] = s_request
        comments = s_request.comments.filter(active=True)
        new_comment = None
        
        # Comment posted
        if request.method == 'POST':
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                # Create Comment object but don't save to database yet
                new_comment = comment_form.save(commit=False)
                # Assign the current request to the comment
                new_comment.creator = request.user
                new_comment.request = s_request
                # Save the comment to the database
                new_comment.save()
                context_dict['new_comment'] = new_comment
            else:
                comment_form = CommentForm()
                context_dict['comment_form'] = comment_form
            
            context_dict['comment_form'] = comment_form
        context_dict['comments'] = comments
    
    except SportRequest.DoesNotExist:
        context_dict['request'] = None
    
    return render(request, 'connectercise/request.html', context=context_dict)



# Add Sport only for Superusers
@login_required
def add_sport(request):
    if request.user.is_superuser:
        form = SportForm()
    
        if request.method == 'POST':
            form = SportForm(request.POST)
            if form.is_valid():
                form.save(commit=True)
                return redirect('/')
            else:
                print(form.errors)
    
        return render(request, 'connectercise/add_sport.html', {'form': form})
    
    else:
        return redirect('/')



# Add Request with Sport Specified
@login_required
def add_sport_request(request, sport_name_slug):
    try:
        sport = Sport.objects.get(slug=sport_name_slug)
    except Sport.DoesNotExist:
        sport = None
    
    if sport is None:
        return redirect('/')
    
    form = SportRequestForm()
    
    if request.method == 'POST':
        form = SportRequestForm(request.POST)
    
        if form.is_valid():
            if sport:
                s_request = form.save(commit=False)
                s_request.sport = sport
                s_request.views = 0
                s_request.creator = request.user
    
                if 'picture' in request.FILES:
                    s_request.picture = request.FILES['picture']
    
                s_request.completed = False
                s_request.save()
                return redirect(reverse('connectercise:show_request', kwargs={'sport_name_slug': sport_name_slug, 'request_name_slug': s_request.request_id}))
        else:
            print(form.errors)
    
    context_dict = {'form': form, 'sport': sport}
    return render(request, 'connectercise/add_request.html', context=context_dict)



# Add Request mentioning the Sport
@login_required
def add_request(request):
    form = RequestForm()
    
    if request.method == 'POST':
        form = RequestForm(request.POST)
    
        if form.is_valid():
            s_request = form.save(commit=False)
            s_request.views = 0
            s_request.creator = request.user
    
            if 'picture' in request.FILES:
                    s_request.picture = request.FILES['picture']
    
            s_request.completed = False
            s_request.save()
            return redirect(reverse('connectercise:show_request', kwargs={'sport_name_slug': s_request.sport, 'request_name_slug': s_request.request_id}))
    
        else:
            print(form.errors)
    context_dict = {'form': form}
    return render(request, 'connectercise/add_request.html', context=context_dict)



# Shows User Profile and Requests they've created
def show_user(request, user_profile_slug):
    context_dict = {}
    try:
        user = User.objects.get(username=user_profile_slug)
        userp = UserProfile.objects.get(user=user)
        context_dict['userp'] = userp
        
        try:
            user_requests = SportRequest.objects.filter(creator=user)
            context_dict['requests'] = user_requests
        except SportRequest.DoesNotExist:
            context_dict['requests'] = None
    
    except User.DoesNotExist:
        context_dict['userp'] = None
    
    return render(request, 'connectercise/user.html', context=context_dict)



# Use Bing Search
def search(request):
    query = request.GET.get('q')
    request_list = None
    
    if query != None:
        request_list = SportRequest.objects.filter(Q(title__icontains=query) | Q(desc__icontains=query)) 
        return render(request, 'connectercise/search.html', {'query': query,'requests': request_list}) 
    
    return render(request, 'connectercise/search.html', {'query': query, 'requests': request_list}) 



@login_required
def accept_request(request, sport_name_slug, request_name_slug):
    s_request = SportRequest.objects.get(slug=request_name_slug)
    # Creators cannot accept their own request
    if s_request.creator != request.user:
        SportRequest.objects.filter(slug=request_name_slug).update(completed=True)
        return redirect(reverse('connectercise:show_user', kwargs={'user_profile_slug': s_request.creator.username}))
    else:
        return redirect(reverse('connectercise:show_request', kwargs={'sport_name_slug': s_request.sport, 'request_name_slug': s_request.request_id}))



@login_required
def delete_request(request, sport_name_slug, request_name_slug):
    s_request = SportRequest.objects.get(slug=request_name_slug)
    # Only the User should be able to delete their own request, and not anyone who goes to the URL
    if s_request.creator == request.user:
        SportRequest.objects.filter(slug=request_name_slug).delete()
        return redirect(reverse('connectercise:show_user', kwargs={'user_profile_slug': s_request.creator.username}))
    else:
        return redirect(reverse('connectercise:show_request', kwargs={'sport_name_slug': s_request.sport, 'request_name_slug': s_request.request_id}))



@login_required
def user_settings(request, user_profile_slug):
    # Only the User should be able to go to settings of their own account, and not anyone who goes to the URL
    if user_profile_slug == request.user.username:
        user_profile = UserProfile.objects.get(user=request.user)
        
        if request.method == "POST":
            update_user_form = UserForm2(data=request.POST, instance=request.user)
            update_profile_form = UserProfileForm(data=request.POST, instance=user_profile)
        
            if update_user_form.is_valid() and update_profile_form.is_valid():
                user = update_user_form.save()
                profile = update_profile_form.save(commit=False)
                profile.user = user
        
                if 'picture' in request.FILES:
                    profile.picture = request.FILES['picture']
        
                profile.save()
                return redirect(reverse('connectercise:show_user', kwargs={'user_profile_slug': user_profile_slug}))
            else:
                print(update_user_form.errors, update_profile_form.errors)
        
        else:
            update_user_form = UserForm2(instance=request.user)

templates/connectercise/activity.html
{% extends 'connectercise/base.html' %}
{% load static %}

{% block title_block %}
    Dashboard
{% endblock %}
{% block body_block %}
<div class="container text-center">
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="activity">Welcome to the activity feed!</h1>
            <div>
            <strong class="activity">Here you can see our most popular sports and our most viewed requests!</strong>
            </div>
        </div>
    </div>
</div>
    <section id="requests" class="bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
            <h2>Most Popular Sports</h2><br>
                        <p class="card-text">
                        {% if sports %}
                        {% for s in sports %}
                            <ul class="list">
                                <li class="list">
                                <img class="list" src="{% static 'images/about4.jpg' %}" />
                                <h3 class="list"><a class="nav-link active" href = "{% url 'connectercise:show_sport' s.slug %}">
                                <span data-feather="archive"></span> {{ s.name }}</a></h3>
                                <p class="list">Check out the latest {{ s.name }} requests!</p>
                                </li>
                            </ul>
                        {% endfor %}
                    {% else %}
                        <li class="nav-item">There are no sports present.</li>
                    {% endif %}
                    </ul>
                    </p>
            </div>
        </div>
    </div>
    </section>
    <br>
    <section id="requests" class="bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
            <h2>Most Viewed Requests</h2><br>
                        <p class="card-text">
                        {% if requests %}
                            {% for r in requests %}
                                <ul class="list">
                                    <li class="list">
                                    <img class="list" src="{% static 'images/about4.jpg' %}" />
                                    <h3 class="list"><a href="{% url 'connectercise:show_request' r.sport.slug r.slug %}">
                                    <span data-feather="archive"></span> {{ r.title }}</a></h3>
                                    <p class="list">{{ r.desc }}</p>
                                    </li>
                                </ul>
                            {% endfor %}
                        {% else %}
                            <li class="nav-item">There are no requests present.</li>
                        {% endif %}
                        </ul>
                        </p>
            </div>
        </div>
    </div>
    </section>
{% endblock %}

templates/connectercise/add_request.html
{% extends 'connectercise/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title_block %}
    Add A Request
{% endblock %}
{% block head_block %}
<script src="{% static 'jQuery/jQuery.js' %}"></script>
{{ form.media }}
{% endblock %}
{% block body_block %}
<div class="container text-center">
    <div class="jumbotron p-4">
        <div class="container">
            <h1>Add a Request</h1>
        </div>
        <hr><br /><br />
        <div class="container">
            {% if sport %}
            <form id="add_request_form" method="POST" action="{% url 'connectercise:add_sport_request' sport.slug %}" enctype="multipart/form-data">
            {% else %}
            <form id="add_request_form" method="POST" action="{% url 'connectercise:add_request' %}" enctype="multipart/form-data">
            {% endif %}
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Create Request</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/connectercise/add_sport.html
{% extends 'connectercise/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title_block %}
    Add A Sport
{% endblock %}
{% block body_block %}
<h1>Add a Sport</h1>
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Sport</h1>
        </div>
    </div>
    <div class="container">
        <div class="row">
        <form role="form" id="sport_form" method="post" action="{% url 'connectercise:add_sport' %}">
        {% csrf_token %}
        {{ form|crispy }}
            <button class="btn btn-primary" type="submit" name="submit">
            Create Sport
            </button>
            <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endblock %}

templates/connectercise/base.html
<!DOCTYPE html>
{% load static %}
{% load connectercise_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Connectercise | {% block title_block %}Connecting People Through Sports{% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <!-- Load icon library for search-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/scrolling-nav.css' %}" rel="stylesheet">
    {% block head_block %}{% endblock %}
    </head>
    
    <body>    
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a style="color: rgb(236, 234, 234);" class="logo" href="{% url 'connectercise:index' %}">
        <span class="menu-collapsed">CONNECTERCISE</span>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'connectercise:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'connectercise:about' %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'connectercise:explore' %}">Explore</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'connectercise:search' %}">Search</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'connectercise:show_user' user.username %}">{{ user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next={% url 'connectercise:index' %}">Logout</a>
            </li>
            {% else %}
             <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
            </li>
            {% endif %}
            <!-- This menu is hidden in bigger devices with d-sm-none. 
           The sidebar isn't proper for smaller screens imo, so this dropdown menu can keep all the useful sidebar itens exclusively for smaller screens  -->
        </ul>
    </div>
</nav><!-- NavBar END -->
        {% if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="wrapper">
                    <!-- Sidebar -->
                    
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                        <a class="logo" href="{% url 'connectercise:index' %}">
                            <span style="margin-left:5%" class="menu-collapsed">CONNECTERCISE</span>
                        </a>
                        <hr>
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'connectercise:index' %}">
                                    <span data-feather="home"></span>
                                    Dashboard <span class="sr-only">(current)</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'connectercise:explore' %}">
                                    <span data-feather="activity"></span>
                                    Explore
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'connectercise:search' %}">
                                    <span data-feather="search"></span>
                                    Search
                                    </a>
                                </li>
                                {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'connectercise:show_user' user.username %}">
                                    <span data-feather="eye"></span>
                                    {{ user.username }}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'connectercise:add_request' %}">
                                    <span data-feather="plus"></span>
                                    Add a Request
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auth_password_change' %}">
                                    <span data-feather="lock"></span>
                                    Change Password
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auth_logout' %}?next={% url 'connectercise:index' %}">
                                    <span data-feather="log-out"></span>
                                    Logout
                                    </a>
                                </li>
                                {% else %}   
                                    <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auth_login' %}">
                                    <span data-feather="log-in"></span>
                                    Login
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </ul>
                    </div>
                    </div>
                </nav>
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
            {% else %}
            <div class="container text-center">
            <main role="main" class="col-lg-8 mx-auto">
            {% endif %}
                    {% block body_block %}
                    {% endblock %}
            <div class="container text-center"
            <footer>
                <hr>
                    <a class="footer" href="{% url 'connectercise:about' %}">About</a> | <a class="footer" href="{% url 'connectercise:privacy_policy' %}">Privacy </a> | <a class="footer" href="{% url 'connectercise:terms_of_service' %}">Terms</a></p>
                    <p class="footer">&copy; 2020 Connectercise 
            </footer>
            </div>
            </main>
            {% if user.is_authenticated %}
            </div>
            {% endif %}
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>